# Generated by Django 6.0.2 on 2026-09-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderFeedback',
        ),
    ]
