# Generated by Django 6.0.2 on 2026-03-29 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('round', 'Round'), ('rectangle', 'Rectangle')], default='round', max_length=20)),
                ('cake_color', models.CharField(default='#683434', max_length=20)),
                ('flavor', models.CharField(choices=[('Choco Moist', 'Choco Moist'), ('Vanilla Chiffon', 'Vanilla Chiffon'), ('Ube Chiffon', 'Ube Chiffon')], default='Choco Moist', max_length=50)),
                ('has_candle', models.BooleanField(default=False)),
                ('has_chocolate', models.BooleanField(default=False)),
                ('has_balls', models.BooleanField(default=False)),
                ('has_nuts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
