# Generated by Django 6.0.2 on 2026-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakecustomization',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='tier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('awaiting_downpayment', 'Awaiting Downpayment'), ('processing', 'Processing'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_review', max_length=30),
        ),
    ]
