# Generated by Django 6.0.2 on 2026-04-24 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_status_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits and start with 09', regex='^09\\d{9}$')]),
        ),
    ]
