# Generated by Django 6.0.2 on 2026-04-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cakecustomization_size_cakecustomization_tier_and_more'),
        ('store', '0011_alter_smsverification_user'),
    ]

    operations = [
    ]
