# Generated by Django 6.0.2 on 2026-04-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_merge_20260426_1715'),
        ('store', '0012_merge_20260426_1736'),
    ]

    operations = [
    ]
