# Generated by Django 6.0.2 on 2026-04-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_barangay_order_region_userprofile_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
    ]
