# Generated by Django 6.0.2 on 2026-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_order_barangay_remove_order_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('awaiting_downpayment', 'Awaiting Downpayment'), ('processing', 'Processing'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_review', max_length=30),
        ),
    ]
