# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_custom_cake_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakecustomization',
            name='inscription_text',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='text_font',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='tier_flavors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='topping_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
