# Generated by Django 6.0.2 on 2026-06-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_cartitem_customization_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakecustomization',
            name='inscription_font',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='inscription_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
