# Generated by Django 6.0.2 on 2026-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakecustomization',
            name='candle_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='has_cherry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='has_sprinkles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='icing_color',
            field=models.CharField(default='#FFF7EA', max_length=20),
        ),
    ]
