# Generated by Django 6.0.2 on 2026-09-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_addonpricing_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('awaiting_customer_response', 'Awaiting Customer Response'), ('awaiting_downpayment', 'Awaiting Downpayment'), ('processing', 'Processing'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_review', max_length=30),
        ),
    ]
