# Generated by Django 6.0.2 on 2026-09-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
